class BadAttributeName(Exception): pass
class BadVariableName(Exception): pass
class BadClassName(Exception): pass
class InvalidInheritance(Exception): pass
class NoMain(Exception): pass
class SelfAssignment(Exception): pass
class BadOperands(Exception): pass
class MethodDoesNotExist(Exception): pass
class BadType(Exception): pass
class CaseIdenticalBranch(Exception): pass
class SelftypeBadReturn(Exception): pass
class InvalidOverride(Exception): pass
class InvalidDispatch(Exception): pass
